---
- copy:
    src: "{{ role_path }}/files/{{item}}"
    dest: /tmp/{{item}}
  with_items:
    - nginx.conf
    - Dockerfile

#- name: Install docker 
#  shell: |
#    curl -fsSL https://get.docker.com | sudo sh
#  when: ansible_pkg_mgr == "apt"
#  register: apt_result

#- name: Docker Build Image
#  become: yes
#  shell: |
#    cat << EOF | docker build --build-args CONF=$(cat -t {{item.key}} -
#    FROM {{item.value}}
#    COPY /tmp/nginx.conf /etc/nginx/nginx.conf
#    RUN echo
#    EOF
#  with_dict: "{{ images }}"
#  register: docker_run
#  tags: docker

- name: Docker Run Nginx image
  #delegate_to: localhost
  #connection: local
  shell: |
      docker run -d -p 80 --name {{ item.key }} {{ item.value }}
  with_dict: "{{ images }}"
  register: docker_run
  tags: docker
- name: debug docker run
  debug: 
    msg: "{{ item }}"
  with_items: docker_run.results
  when: docker_run is failed
  tags: [ 'never', 'debug' ]

- name: Docker Commit Container
  #delegate_to: localhost
  #connection: local
  shell: |
      docker commit {{ item.key }} repo/{{ item.key }}
  with_dict: "{{ images }}"
  tags: [ 'never', 'commit', 'stop' ]

- name: Docker Stop Container
  shell: |
      docker stop {{ item.key }}
  with_dict: "{{ images }}"
  tags: [ 'never', 'stop' ]
